name: Generate Coverage Badge

on:
    push:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci --ignore-scripts
      - run: npm run coverage
      - run: npm i coverage-badges-cli -g
      - run: coverage-badges --output coverage/badges.svg

      - name: Deploy Coverage Badge
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          publish_branch: main

  