name: Push Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci --ignore-scripts
      - run: npm run test
      - run: npm run coverage
      - run: npm i coverage-badges-cli -g
      - run: coverage-badges --output coverage/badges.svg

  